site_name: B Horn
site_url: https://b.horn.uk/
site_description: |
  I'm a Software developer with an interest in remote sensing, infosec and embedded development.

nav:
  - Home: 'index.md'
    #- Projects:
    #- 'projects/index.md'
  - About:
    - 'about/index.md'

theme:
  name: material
  palette:
    primary: 'purple'
    accent: 'purple'
  icon:
    logo: fontawesome/solid/robot
    repo: fontawesome/brands/git-alt

  features:
    - tabs
    - instant

  custom_dir: 'theme'

extra:
  social:
    - icon: material/github
      link: https://github.com/bahorn
      alt: GitHub
    - icon: material/gitlab
      link: https://gitlab.com/bahorn
      alt: GitLab
    - icon: material/code-brackets
      link: https://devpost.com/bahorn
      alt: Devpost

plugins:
  - search
  - git-revision-date-localized:
      type: date
  - minify:
      minify_html: true
